language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database etrader;' -U monsiper
# command to run tests
script: 
  - ./manage.py test
