language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: 
  - psql -c 'create user monsiper with createdb';
  - ./manage.py test
