# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-09 17:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.DecimalField(decimal_places=3, max_digits=8)),
                ('coin', models.DecimalField(decimal_places=3, max_digits=8)),
                ('buy_limit', models.DecimalField(decimal_places=3, max_digits=8)),
                ('sell_limit', models.DecimalField(decimal_places=3, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timestamp_latest_activity', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('processing_lock', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Buy', 'BUY'), ('Sell', 'SELL')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=8)),
                ('order_status', models.CharField(choices=[('Pending', 'Order is pending'), ('Success', 'Order has executed'), ('Fail', 'Order has failed')], default='Pending', max_length=10)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
