# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-07 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20161110_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='EthereumPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=30, max_digits=40)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='buy_limit',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=7),
        ),
        migrations.AlterField(
            model_name='account',
            name='cash',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='account',
            name='coin',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='account',
            name='sell_limit',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
