# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-12 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20161207_2120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EthereumPrice',
        ),
        migrations.RemoveField(
            model_name='account',
            name='processing_lock',
        ),
    ]
